[package]
name = "sg2002-c906l-static"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[lib]
crate-type = ["staticlib"]

[features]
default = []
timer4 = ["sg2002-c906l-firmware/timer4"]
timer5 = ["sg2002-c906l-firmware/timer5"]
timer6 = ["sg2002-c906l-firmware/timer6"]
timer7 = ["sg2002-c906l-firmware/timer7"]
picoclaw-lcd = ["sg2002-c906l-firmware/picoclaw-lcd"]

[dependencies]
sg2002-c906l-firmware = { path = ".." }
